### ISSUE TITLE
icons do not appear

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.sourceforge.Klavaro#1]
![captura de tela de 2017-10-20 13-09-48](https://user-images.githubusercontent.com/26097419/31828203-58e05df0-b598-11e7-94d6-8b0bf602c3f1.png)

**Comment by nedrichards** [comment]
Error messages on the command line are:

`(klavaro:3): Gtk-WARNING **: Error loading theme icon 'dialog-warning' for stock: Icon 'dialog-warning' not present in theme EndlessOS
(klavaro:3): Gtk-WARNING **: Error loading theme icon 'format-text-strikethrough' for stock: Icon 'format-text-strikethrough' not present in theme EndlessOS
(klavaro:3): Gtk-WARNING **: Error loading theme icon 'format-text-bold' for stock: Icon 'format-text-bold' not present in theme EndlessOS
(klavaro:3): Gtk-WARNING **: Error loading theme icon 'tools-check-spelling' for stock: Icon 'tools-check-spelling' not present in theme EndlessOS
(klavaro:3): Gtk-WARNING **: Error loading theme icon 'help-contents' for stock: Icon 'help-contents' not present in theme EndlessOS
(klavaro:3): Gtk-WARNING **: Error loading theme icon 'help-about' for stock: Icon 'help-about' not present in theme EndlessOS
(klavaro:3): Gtk-WARNING **: Error loading theme icon 'window-close' for stock: Icon 'window-close' not present in theme EndlessOS
`

I'll take a look at this.

**Comment by TingPing** [comment]
The fdo runtime doesn't include icons and you need an up to date `flatpak` to use icons from the host.

**Comment by nedrichards** [comment]
Ah, OK - will build some icons in for now - we can remove later when recent flatpaks have disseminated.

**Comment by nedrichards** [comment]
This should be fixed in https://github.com/flathub/net.sourceforge.Klavaro/commit/88c6e94f139b2f42420ae5f0aa73e8dd8fe78c59

**Comment by wieczorek1990** [comment]
`brew install adwaita-icon-theme`
