### ISSUE TITLE
Update to 3.13 and freedesktop 21.08

### ISSUE THREAD

**Issue by jorgeml** [flathub/net.sourceforge.Klavaro#7]
3.13 is out and the current flatpak is based on freedesktop 18.08 so it throws this error:

```
Info: org.freedesktop.Platform//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   net.sourceforge.Klavaro
```

Unfortunately I have no experience with flatpaks so I can't help much.

Thanks in advance!

**Comment by hfiguiere** [comment]
Just merged an update to the 20.08 runtime and 3.12 version of the app that was submitted.

This should help in the meantime.
